load("@build_bazel_rules_apple//apple:apple.bzl", "apple_dynamic_xcframework_import")

apple_dynamic_xcframework_import(
    name = "Lottie",
    visibility = ["//visibility:public"],
    xcframework_imports = glob(["Lottie.xcframework/**"]),
)
